// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-HuAKLayPXUVrk5LR8Ok5xN2Iz7HM5c',
    appId: '1:621097076279:web:e3f607764ad8404583a1b2',
    messagingSenderId: '621097076279',
    projectId: 'djbc-30a88',
    authDomain: 'djbc-30a88.firebaseapp.com',
    storageBucket: 'djbc-30a88.appspot.com',
    measurementId: 'G-4Z6ZDB7RVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqrePCtJm3Okxag-yrK6mKKsp3X7chTxA',
    appId: '1:621097076279:android:41f850ec9bbd314683a1b2',
    messagingSenderId: '621097076279',
    projectId: 'djbc-30a88',
    storageBucket: 'djbc-30a88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdO0I947Oe58gI6z3hmBpj2mV4HV6mLJU',
    appId: '1:621097076279:ios:7a68e038762e1afe83a1b2',
    messagingSenderId: '621097076279',
    projectId: 'djbc-30a88',
    storageBucket: 'djbc-30a88.appspot.com',
    iosBundleId: 'com.example.satubc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdO0I947Oe58gI6z3hmBpj2mV4HV6mLJU',
    appId: '1:621097076279:ios:7a68e038762e1afe83a1b2',
    messagingSenderId: '621097076279',
    projectId: 'djbc-30a88',
    storageBucket: 'djbc-30a88.appspot.com',
    iosBundleId: 'com.example.satubc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG-HuAKLayPXUVrk5LR8Ok5xN2Iz7HM5c',
    appId: '1:621097076279:web:4ee67234d5b080d683a1b2',
    messagingSenderId: '621097076279',
    projectId: 'djbc-30a88',
    authDomain: 'djbc-30a88.firebaseapp.com',
    storageBucket: 'djbc-30a88.appspot.com',
    measurementId: 'G-MDXF2TVKTB',
  );

}